@SariSariStore.WebApi_HostAddress = https://192.168.100.60:7211

GET {{SariSariStore.WebApi_HostAddress}}/index.html

###

GET {{SariSariStore.WebApi_HostAddress}}/api/Product/1  
Accept: application/json

###

POST {{SariSariStore.WebApi_HostAddress}}/api/Product/
Content-Type: application/json

### 

GET {{SariSariStore.WebApi_HostAddress}}/api/Orders/